[package]
name = "ga-web"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
generative-art = {path = "../generative-art/"}
dashmap = "4.0.2"
blake3 = "1.0.0"
hex = "0.4.3"