[tasks.format]
description = "Formats the WASM rust code."
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean-wasm]
description = "Removes old WASM rust builds."
script_runner = "@duckscript"
script = "rm -Rf pkg && cargo clean"

[tasks.build-wasm]
description = "Builds the WASM."
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
command = "wasm-pack"
args = ["build", "--release"]

[tasks.clean-site]
description = "Removes old site builds."
cwd = "www"
script_runner = "@duckscript"
script = "rm -Rf dist node_modules package-lock.json"

[tasks.build-site]
cwd = "www"
script = '''
npm install
npm run build
'''

[tasks.full-clean-flow]
dependencies = ["clean-wasm", "clean-site"]

[tasks.full-build-flow]
dependencies = ["full-clean-flow", "format", "build-wasm", "build-site"]

[tasks.iter-build-flow]
dependencies = ["format", "build-wasm", "build-site"]

[tasks.run]
description = "Build the site and start a development server."
dependencies = ["iter-build-flow"]
cwd = "www"
script = "npm run start"
